/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import forma.panel.PnlPretragaKlijenta;
import forma.panel.PnlPretragaRezervacije;
import forma.panel.PnlPretragaVozila;
import forma.panel.PnlRezervacija;
import forma.panel.PnlUnajmljivanje;
import forma.panel.PnlUnosKlijenta;
import forma.panel.PnlUnosVozila;
import javax.swing.JOptionPane;
import sesija.Sesija;

/**
 *
 * @author Sapsaj
 */
public class GlavnaForma extends javax.swing.JFrame {

    FrmForma forma;
    FrmDialog dialog;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();

        kontroler.Kontroler.getInstanca().setForma(this);
        showForm();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrijavljeni = new javax.swing.JPanel();
        lblPrijavljeniZaposleni = new javax.swing.JLabel();
        btnOdjaviSe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKlijenti = new javax.swing.JMenu();
        menuPretragaKlijenta = new javax.swing.JMenuItem();
        menuUnosKlijenta = new javax.swing.JMenuItem();
        menuVozila = new javax.swing.JMenu();
        menuPretragaVozila = new javax.swing.JMenuItem();
        menuUnosVozila = new javax.swing.JMenuItem();
        menuRezervacija = new javax.swing.JMenu();
        menuItemUnosRezervacije = new javax.swing.JMenuItem();
        jMenuItemPretrafaRezervacije = new javax.swing.JMenuItem();
        menuUnajmljivanje = new javax.swing.JMenu();
        jMenuUnosUnajmljivanja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        setBounds(new java.awt.Rectangle(500, 300, 450, 300));
        setPreferredSize(new java.awt.Dimension(674, 422));

        pnlPrijavljeni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPrijavljeniZaposleni.setText("Ulogovani");

        btnOdjaviSe.setText("Odjavi se");
        btnOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrijavljeniLayout = new javax.swing.GroupLayout(pnlPrijavljeni);
        pnlPrijavljeni.setLayout(pnlPrijavljeniLayout);
        pnlPrijavljeniLayout.setHorizontalGroup(
            pnlPrijavljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrijavljeniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPrijavljeniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnOdjaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlPrijavljeniLayout.setVerticalGroup(
            pnlPrijavljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrijavljeniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrijavljeniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrijavljeniZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdjaviSe))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        menuKlijenti.setText("Klijenti");

        menuPretragaKlijenta.setText("Preteraga/izmena klijenta");
        menuPretragaKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaKlijentaActionPerformed(evt);
            }
        });
        menuKlijenti.add(menuPretragaKlijenta);

        menuUnosKlijenta.setText("Unos klijenta");
        menuUnosKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosKlijentaActionPerformed(evt);
            }
        });
        menuKlijenti.add(menuUnosKlijenta);

        jMenuBar1.add(menuKlijenti);

        menuVozila.setText("Vozila");

        menuPretragaVozila.setText("Pretraga vozila");
        menuPretragaVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPretragaVozilaActionPerformed(evt);
            }
        });
        menuVozila.add(menuPretragaVozila);

        menuUnosVozila.setText("Unos vozila");
        menuUnosVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnosVozilaActionPerformed(evt);
            }
        });
        menuVozila.add(menuUnosVozila);

        jMenuBar1.add(menuVozila);

        menuRezervacija.setText("Rezervacija");

        menuItemUnosRezervacije.setText("Unos rezervacije");
        menuItemUnosRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUnosRezervacijeActionPerformed(evt);
            }
        });
        menuRezervacija.add(menuItemUnosRezervacije);

        jMenuItemPretrafaRezervacije.setText("Pretraga rezervacije");
        jMenuItemPretrafaRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretrafaRezervacijeActionPerformed(evt);
            }
        });
        menuRezervacija.add(jMenuItemPretrafaRezervacije);

        jMenuBar1.add(menuRezervacija);

        menuUnajmljivanje.setText("Unajmljivanje");

        jMenuUnosUnajmljivanja.setText("Unos unajmljivanja");
        jMenuUnosUnajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnosUnajmljivanjaActionPerformed(evt);
            }
        });
        menuUnajmljivanje.add(jMenuUnosUnajmljivanja);

        jMenuBar1.add(menuUnajmljivanje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(pnlPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUnosVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosVozilaActionPerformed
        PnlUnosVozila pv = new PnlUnosVozila(ModForme.unos);
        dialog = new FrmDialog(this, true, pv);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuUnosVozilaActionPerformed

    private void btnOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviSeActionPerformed
        try {
            String odgovor = kontroler.Kontroler.getInstanca().odjavaSaSistema(Sesija.getInstanca().getZaposleni());
            JOptionPane.showMessageDialog(this, odgovor);
            FrmPrijavljivanje form = new FrmPrijavljivanje();
            form.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOdjaviSeActionPerformed

    private void menuUnosKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnosKlijentaActionPerformed
        PnlUnosKlijenta pk = new PnlUnosKlijenta(ModForme.unos);
        dialog = new FrmDialog(this, true, pk);
        dialog.setVisible(true);

    }//GEN-LAST:event_menuUnosKlijentaActionPerformed

    private void menuPretragaKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaKlijentaActionPerformed
        PnlPretragaKlijenta pk = new PnlPretragaKlijenta();
        forma = new FrmForma(pk);
        forma.setVisible(true);
    }//GEN-LAST:event_menuPretragaKlijentaActionPerformed

    private void menuPretragaVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPretragaVozilaActionPerformed
        PnlPretragaVozila panel = new PnlPretragaVozila();
        forma = new FrmForma(panel);
        forma.setVisible(true);
    }//GEN-LAST:event_menuPretragaVozilaActionPerformed

    private void menuItemUnosRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUnosRezervacijeActionPerformed
        PnlRezervacija ps = new PnlRezervacija(ModForme.unos);
        sesija.Sesija.getInstanca().getMapa().put("trenutniKlijent", null);
        sesija.Sesija.getInstanca().getMapa().put("trenutnoVozilo", null);

        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_menuItemUnosRezervacijeActionPerformed

    private void jMenuItemPretrafaRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretrafaRezervacijeActionPerformed
        PnlPretragaRezervacije ps = new PnlPretragaRezervacije();
        forma = new FrmForma(ps);
        forma.setVisible(true);
    }//GEN-LAST:event_jMenuItemPretrafaRezervacijeActionPerformed

    private void jMenuUnosUnajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnosUnajmljivanjaActionPerformed
        PnlUnajmljivanje ps = new PnlUnajmljivanje(ModForme.unos);
        forma = new FrmForma(ps);
        forma.setVisible(true);

    }//GEN-LAST:event_jMenuUnosUnajmljivanjaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjaviSe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPretrafaRezervacije;
    private javax.swing.JMenuItem jMenuUnosUnajmljivanja;
    private javax.swing.JLabel lblPrijavljeniZaposleni;
    private javax.swing.JMenuItem menuItemUnosRezervacije;
    private javax.swing.JMenu menuKlijenti;
    private javax.swing.JMenuItem menuPretragaKlijenta;
    private javax.swing.JMenuItem menuPretragaVozila;
    private javax.swing.JMenu menuRezervacija;
    private javax.swing.JMenu menuUnajmljivanje;
    private javax.swing.JMenuItem menuUnosKlijenta;
    private javax.swing.JMenuItem menuUnosVozila;
    private javax.swing.JMenu menuVozila;
    private javax.swing.JPanel pnlPrijavljeni;
    // End of variables declaration//GEN-END:variables

    public void showForm() {
        setVisible(true);
        setLocationRelativeTo(null);
        //setResizable(false);
        lblPrijavljeniZaposleni.setText("Dobro došli " + sesija.Sesija.getInstanca().getZaposleni().getImePrezimeZaposleni());
    }
}
