/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma;

import domain.Zaposleni;
import forma.model.TableModel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import niti.PokretanjeServera;

/**
 *
 * @author lizasapsaj
 */
public class GlavnaForma extends javax.swing.JFrame {
    PokretanjeServera ps;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        srediTabelu();
        pnlZaposleni.setVisible(false);
        postaviStatus("Server nije pokrenut", true);
        Kontroler.getInstanca().setForma(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        pnlKonfiguracija = new javax.swing.JPanel();
        btnKonfiguracijaBaze = new javax.swing.JButton();
        btnKonfiguracijaKonekcije = new javax.swing.JButton();
        pnlZaposleni = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblZaposleni = new javax.swing.JTable();
        btnOdjaviZaposlenog = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatus.setText("Server nije pokrenut!");

        btnPokreni.setText("Pokreni");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        pnlKonfiguracija.setBorder(javax.swing.BorderFactory.createTitledBorder("Konfiguracija"));

        btnKonfiguracijaBaze.setText("Konfiguracija baze");
        btnKonfiguracijaBaze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfiguracijaBazeActionPerformed(evt);
            }
        });

        btnKonfiguracijaKonekcije.setText("Konfiguracija konekcije");
        btnKonfiguracijaKonekcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfiguracijaKonekcijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKonfiguracijaLayout = new javax.swing.GroupLayout(pnlKonfiguracija);
        pnlKonfiguracija.setLayout(pnlKonfiguracijaLayout);
        pnlKonfiguracijaLayout.setHorizontalGroup(
            pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonfiguracijaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnKonfiguracijaBaze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnKonfiguracijaKonekcije)
                .addGap(20, 20, 20))
        );
        pnlKonfiguracijaLayout.setVerticalGroup(
            pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKonfiguracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKonfiguracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKonfiguracijaBaze)
                    .addComponent(btnKonfiguracijaKonekcije))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlZaposleni.setBorder(javax.swing.BorderFactory.createTitledBorder("Zaposleni"));

        tblZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblZaposleni);

        btnOdjaviZaposlenog.setText("Odjavi zaposlenog");
        btnOdjaviZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviZaposlenogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlZaposleniLayout = new javax.swing.GroupLayout(pnlZaposleni);
        pnlZaposleni.setLayout(pnlZaposleniLayout);
        pnlZaposleniLayout.setHorizontalGroup(
            pnlZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaposleniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdjaviZaposlenog)
                .addGap(15, 15, 15))
        );
        pnlZaposleniLayout.setVerticalGroup(
            pnlZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZaposleniLayout.createSequentialGroup()
                .addGroup(pnlZaposleniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlZaposleniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlZaposleniLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnOdjaviZaposlenog)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPokreni)
                                .addGap(61, 61, 61)
                                .addComponent(btnZaustavi))
                            .addComponent(lblStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pnlKonfiguracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblStatus)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addGap(18, 18, 18)
                .addComponent(pnlKonfiguracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        ps = new PokretanjeServera();
        ps.start();
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        ps.zaustaviServer();
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void btnKonfiguracijaBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfiguracijaBazeActionPerformed
        FrmKonfiguracijaBaze frm=new FrmKonfiguracijaBaze(this, true);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnKonfiguracijaBazeActionPerformed

    private void btnKonfiguracijaKonekcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfiguracijaKonekcijeActionPerformed
        FrmKonfiguraciaKonekcije frm=new FrmKonfiguraciaKonekcije(this, true);
        frm.setLocationRelativeTo(null);
        frm.pack();
        frm.setVisible(true);
    }//GEN-LAST:event_btnKonfiguracijaKonekcijeActionPerformed

    private void btnOdjaviZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviZaposlenogActionPerformed
       TableModel model = (TableModel) tblZaposleni.getModel();
        int index = tblZaposleni.getSelectedRow();
        if (index != -1) {
            Zaposleni z = model.izbaciRed(index);
            Kontroler.getInstanca().izbaciZaposlenog(z);
        } else {
            JOptionPane.showMessageDialog(this, "Morate izabrati red tabele!");
        }
    }//GEN-LAST:event_btnOdjaviZaposlenogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfiguracijaBaze;
    private javax.swing.JButton btnKonfiguracijaKonekcije;
    private javax.swing.JButton btnOdjaviZaposlenog;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlKonfiguracija;
    private javax.swing.JPanel pnlZaposleni;
    private javax.swing.JTable tblZaposleni;
    // End of variables declaration//GEN-END:variables
 private void srediTabelu() {
        TableModel model = new TableModel();
        tblZaposleni.setModel(model);
    }

    public void dodajPrijavljenogZaposlenog(Zaposleni z) {
        TableModel model = (TableModel) tblZaposleni.getModel();
        model.dodajZaposlenog(z);
    }

    public void odjaviZaposlenog(Zaposleni z) {
        TableModel model = (TableModel) tblZaposleni.getModel();
        model.izbaciZaposlenog(z);
    }

    public void popuniTabelu() {
        TableModel model = new TableModel();
        tblZaposleni.setModel(model);
    }

    public void postaviStatus(String poruka, boolean signal) {

        lblStatus.setText(poruka);
        btnPokreni.setEnabled(signal);
        btnZaustavi.setEnabled(!signal);
        pnlZaposleni.setVisible(!signal);
        pnlKonfiguracija.setVisible(signal);

    }

}
