/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domain.Klijent;
import forma.FrmDialog;
import forma.FrmForma;
import forma.IPanel;
import forma.ModForme;
import forma.model.ModelTabeleKlijent;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sapsaj
 */
public class PnlPretragaKlijenta extends javax.swing.JPanel implements IPanel {

    ModelTabeleKlijent model;

    /**
     * Creates new form PnlPretragaKlijenta
     */
    public PnlPretragaKlijenta() {
        initComponents();
        pripremiTabelu();
        btnIzaberi.setVisible(false);
        vratiSve();
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImePrezime = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnVratiSve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();
        btnUnesiNovog = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnPrikaziDetalje = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();

        lblImePrezime.setText("Ime i prezime:");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnVratiSve.setText("Vrati sve");
        btnVratiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiSveActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijenti);

        btnUnesiNovog.setText("Unesi novog");
        btnUnesiNovog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiNovogActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikaziDetalje.setText("Prikazi detalje");
        btnPrikaziDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblImePrezime)
                        .addGap(18, 18, 18)
                        .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUnesiNovog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVratiSve)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrikaziDetalje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzaberi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImePrezime)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnVratiSve))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnUnesiNovog)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziDetalje)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzaberi)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVratiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiSveActionPerformed
        try {
            model = new ModelTabeleKlijent();
            List<Klijent> lista = kontroler.Kontroler.getInstanca().vratiSveKlijente();

            for (Klijent k : lista) {
                model.ubaci(k);
            }
            tblKlijenti.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_btnVratiSveActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String imeIPrezime = txtImePrezime.getText();
        if (imeIPrezime.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli kriterijum izbora");
            return;
        }
        Klijent kl = new Klijent();
        kl.setImePrezimeKlijent(imeIPrezime);
        List<Klijent> lista;
        model = new ModelTabeleKlijent();
        try {
            lista = kontroler.Kontroler.getInstanca().vratiKlijente(kl);

            for (Klijent k : lista) {
                model.ubaci(k);
            }
            tblKlijenti.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            vratiSve();
            Logger.getLogger(PnlPretragaKlijenta.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnUnesiNovogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiNovogActionPerformed
        pripremiDialog(ModForme.unos);
    }//GEN-LAST:event_btnUnesiNovogActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        pripremiDialog(ModForme.izmena);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeActionPerformed
       pripremiDialog(ModForme.pregled);
    }//GEN-LAST:event_btnPrikaziDetaljeActionPerformed

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        int index = tblKlijenti.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati red u tabeli");
            return;
        }
        Klijent k = model.getLista().get(index);
        sesija.Sesija.getInstanca().getMapa().put("trenutniKlijent", k);
        (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
        ((FrmForma) SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_btnIzaberiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziDetalje;
    private javax.swing.JButton btnUnesiNovog;
    private javax.swing.JButton btnVratiSve;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtImePrezime;
    // End of variables declaration//GEN-END:variables

    private void pripremiTabelu() {
        model = new ModelTabeleKlijent();
        tblKlijenti.setModel(model);
    }

    private void pripremiDialog(ModForme modForme) {
        if (modForme != ModForme.unos) {
            int index = tblKlijenti.getSelectedRow();

            if (index == -1) {

                JOptionPane.showMessageDialog(this, "Morate izabrati red!");
                return;
            }
            Klijent k = model.getLista().get(index);
            sesija.Sesija.getInstanca().getMapa().put("trenutniKlijent", k);
        }

        PnlUnosKlijenta panel = new PnlUnosKlijenta(modForme);
        FrmDialog dialog = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
        dialog.setVisible(true);
    }

    void izaberi() {
         btnIzaberi.setVisible(true);
    }

    private void vratiSve() {
        try {
            model = new ModelTabeleKlijent();
            List<Klijent> lista = kontroler.Kontroler.getInstanca().vratiSveKlijente();

            for (Klijent k : lista) {
                model.ubaci(k);
            }
            tblKlijenti.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }
}
