/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import domain.Klijent;
import domain.OpstaDomenskaKlasa;
import domain.Rezervacija;
import domain.Vozilo;
import forma.FrmDialog;
import forma.FrmForma;
import forma.GlavnaForma;
import forma.IPanel;
import forma.ModForme;
import forma.model.ModelTabeleRezervacija;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;

/**
 *
 * @author Sapsaj
 */
public class PnlRezervacija extends javax.swing.JPanel implements IPanel {

    Vozilo v;
    Klijent k;
    ModForme mod;
    ModelTabeleRezervacija model;

    /**
     * Creates new form PnlRezervacija
     */
    public PnlRezervacija(ModForme modForme) {
        mod = modForme;
        initComponents();
        pripremiFormu();
        dpDatum.setEnabled(false);
        txtCenaRezervacije.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMarka = new javax.swing.JLabel();
        lblKilometraza = new javax.swing.JLabel();
        lblTipVozila = new javax.swing.JLabel();
        lblBrojPutnila = new javax.swing.JLabel();
        lblCenaPoDanu = new javax.swing.JLabel();
        btnIzborVozila = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblImeIPrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblBrojTelefona = new javax.swing.JLabel();
        btnIzborKlijenta = new javax.swing.JButton();
        lblNazivRezervacije = new javax.swing.JLabel();
        txtNazivRezervacije = new javax.swing.JTextField();
        jPnl2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezervacija = new javax.swing.JTable();
        btnPrikaziDetalje = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnUnesi = new javax.swing.JButton();
        lblCenaRezervacije = new javax.swing.JLabel();
        txtCenaRezervacije = new javax.swing.JTextField();
        btnSacuvajSve = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblDatumRezervacije = new javax.swing.JLabel();
        dpDatum = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        dpDatumOd = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        dpDatumDo = new datechooser.beans.DateChooserCombo();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o vozilu"));

        lblMarka.setText("Marka vozila:");

        lblKilometraza.setText("Kilometraza:");

        lblTipVozila.setText("Tip vozila:");

        lblBrojPutnila.setText("Broj putnika:");

        lblCenaPoDanu.setText("Cena po danu:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarka)
                    .addComponent(lblKilometraza)
                    .addComponent(lblTipVozila)
                    .addComponent(lblBrojPutnila)
                    .addComponent(lblCenaPoDanu))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblMarka)
                .addGap(18, 18, 18)
                .addComponent(lblKilometraza)
                .addGap(18, 18, 18)
                .addComponent(lblTipVozila)
                .addGap(18, 18, 18)
                .addComponent(lblBrojPutnila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblCenaPoDanu)
                .addGap(22, 22, 22))
        );

        btnIzborVozila.setText("Izaberi vozilo");
        btnIzborVozila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborVozilaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o klijentu"));

        lblImeIPrezime.setText("Ime i prezime:");

        lblDatumRodjenja.setText("Datum rodjenja:");

        lblBrojTelefona.setText("Broj telefona:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrojTelefona)
                    .addComponent(lblDatumRodjenja)
                    .addComponent(lblImeIPrezime))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblImeIPrezime)
                .addGap(27, 27, 27)
                .addComponent(lblDatumRodjenja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblBrojTelefona)
                .addContainerGap())
        );

        btnIzborKlijenta.setText("Izaberi klijenta");
        btnIzborKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzborKlijentaActionPerformed(evt);
            }
        });

        lblNazivRezervacije.setText("Naziv rezervacije:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervacija"));

        tblRezervacija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezervacija);

        btnPrikaziDetalje.setText("Prikazi detalje");
        btnPrikaziDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrikaziDetalje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnPrikaziDetalje)
                        .addGap(50, 50, 50)
                        .addComponent(btnObrisi)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnUnesi.setText("Unesi");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl2Layout = new javax.swing.GroupLayout(jPnl2);
        jPnl2.setLayout(jPnl2Layout);
        jPnl2Layout.setHorizontalGroup(
            jPnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jPnl2Layout.setVerticalGroup(
            jPnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUnesi)
                .addGap(38, 38, 38)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCenaRezervacije.setText("Cena rezervacije:");

        btnSacuvajSve.setText("Sacuvaj sve");
        btnSacuvajSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajSveActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDatumRezervacije.setText("Datum rezervacije:");

        dpDatum.setLocale(new java.util.Locale("sr", "BA", ""));

        jLabel1.setText("Datum od:");

        dpDatumOd.setLocale(new java.util.Locale("sr", "BA", ""));

        jLabel2.setText("Datum do:");

        dpDatumDo.setLocale(new java.util.Locale("sr", "BA", ""));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDatumRezervacije)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dpDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumRezervacije))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dpDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dpDatumDo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnIzborVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzborKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCenaRezervacije)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCenaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNazivRezervacije)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNazivRezervacije))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSacuvajSve)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzborVozila)
                            .addComponent(btnIzborKlijenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNazivRezervacije)
                            .addComponent(txtNazivRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCenaRezervacije)
                            .addComponent(txtCenaRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPnl2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnSacuvajSve)))
                .addGap(269, 269, 269))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzborKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborKlijentaActionPerformed
        PnlPretragaKlijenta panel = new PnlPretragaKlijenta();
        panel.izaberi();
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnIzborKlijentaActionPerformed

    private void btnIzborVozilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzborVozilaActionPerformed
        PnlPretragaVozila panel = new PnlPretragaVozila();
        panel.izaberi();
        FrmForma forma = new FrmForma(panel);
        forma.setParent((Frame) SwingUtilities.getWindowAncestor(this));
        forma.setVisible(true);
    }//GEN-LAST:event_btnIzborVozilaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int index = tblRezervacija.getSelectedRow();
        if (index == -1) {

            JOptionPane.showMessageDialog(this, "Morate izabrati red");
            return;
        }

        Rezervacija r = model.getLista().get(index);

        model.izbaci(r);


    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        System.out.println("Uslo u unesi!");
        
         String naziv = txtNazivRezervacije.getText();
        String cena = txtCenaRezervacije.getText();
        Date d = new Date();

        Date datumOd = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date datumDo = new Date();

       if(naziv=="" || naziv.isEmpty()){
             JOptionPane.showMessageDialog(this, "Morate uneti naziv");
             return;
    }
        try { 
            datumOd = java.sql.Date.valueOf(format.format(dpDatumOd.getSelectedDate().getTime()));
            d = java.sql.Date.valueOf(format.format(dpDatum.getSelectedDate().getTime()));
            if (datumOd.before(new Date())) {
                JOptionPane.showMessageDialog(this, "Pocetak rezervacije ne moze biti pre danasnjeg datuma");
                return;
            }
            datumDo = java.sql.Date.valueOf(format.format(dpDatumDo.getSelectedDate().getTime()));
            if (datumDo.before(datumOd)) {
                JOptionPane.showMessageDialog(this, "Kraj rezervacije ne moze biti pre pocetka rezervacije");
                return;
            }
            int days = daysBetween(datumOd, datumDo);
            double konacna = v.getCenaPoDanu() * days;
            txtCenaRezervacije.setText(konacna + "");

           

            if (validacija(txtNazivRezervacije.getText(), konacna + "")) {
               
                System.out.println("NAZIV"+naziv);
                Rezervacija nova = new Rezervacija((long) 0, naziv, d, datumOd, datumDo, konacna, v, k);

                if (v == null || k == null) {
                    JOptionPane.showMessageDialog(this, "Morate uneti klijenta i vozilo");
                    return;
                }

                ArrayList<Rezervacija> lista = new ArrayList<>();
                try {
                    lista = (ArrayList<Rezervacija>) kontroler.Kontroler.getInstanca().vratiRezervacije();
                } catch (Exception ex) {

                }
                try {
                    if (!model.getLista().isEmpty()) {
                        System.out.println(nova.getKlijent().getIdKlijent());
                        for (Rezervacija rez : model.getLista()) {
                            System.out.println("Lista klijent; " + rez.getKlijent().getIdKlijent());
                            if (rez.getKlijent().getIdKlijent().equals(nova.getKlijent().getIdKlijent())
                                    && (nova.getDatumOd().compareTo(rez.getDatumOd()) == 0 || (nova.getDatumOd().compareTo(rez.getDatumOd()) > 0
                                    && nova.getDatumOd().compareTo(rez.getDatumDo()) < 0))) {
                                throw new Exception("Isti klijent ne moze da rezervise 2 vozila u istom periodu");

                            }
                        }
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    v = null;
                    k = null;
                    izmeniPolja();
                    return;

                }
                model.ubaci(nova);
                v = null;
                k = null;

                izmeniPolja();
                sesija.Sesija.getInstanca().getMapa().put("trenutnoVozilo", null);
                sesija.Sesija.getInstanca().getMapa().put("trenutniKlijent", null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Morate uneti datum rezervacije");
            e.printStackTrace();
            return;
        }


    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnPrikaziDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeActionPerformed
        pripremiDialog(ModForme.pregled);
    }//GEN-LAST:event_btnPrikaziDetaljeActionPerformed

    private void btnSacuvajSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajSveActionPerformed
        List<Rezervacija> a = model.getLista();
        if (a.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Niste uneli ni jednu rezervaciju");
            return;
        }
        try {
            String poruka = Kontroler.getInstanca().unesiRezervacije(a);
            JOptionPane.showMessageDialog(this, poruka);

            ((FrmForma) SwingUtilities.getWindowAncestor(this)).dispose();
            if (((SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
                return;
            }
            sesija.Sesija.getInstanca().setRezervacije(a);
            (((FrmForma) SwingUtilities.getWindowAncestor((FrmForma) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();

        } catch (NullPointerException ex) {
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno cuvanje");
            //Logger.getLogger(PnlStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajSveActionPerformed

    private void pripremiFormu() {
        switch (mod) {
            case unos:
                btnSacuvajSve.setVisible(true);

                model = new ModelTabeleRezervacija();
                tblRezervacija.setModel(model);
                break;
            case izmena:
                jPnl2.setVisible(false);
                btnUnesi.setVisible(false);
                btnSacuvajSve.setVisible(false);

                btnIzborVozila.setVisible(false);
                btnIzborKlijenta.setVisible(false);
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutnaRezervacija"));
                break;
            case pregled:
                jPnl2.setVisible(false);
                btnUnesi.setVisible(false);
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutnaRezervacija"));
                btnSacuvajSve.setVisible(false);
                txtCenaRezervacije.setEditable(false);
                btnIzborVozila.setVisible(false);
                btnIzborKlijenta.setVisible(false);
                break;
        }

    }

    private void pripremiDialog(ModForme modForme) {
        if (modForme != ModForme.unos) {
            int index = tblRezervacija.getSelectedRow();

            if (index == -1) {

                JOptionPane.showMessageDialog(this, "Morate izabrati red!");
                return;
            }
            Rezervacija r = model.getLista().get(index);

            sesija.Sesija.getInstanca().getMapa().put("trenutnaRezervacija", r);
            PnlRezervacija panel = new PnlRezervacija(modForme);
            FrmDialog dialog = new FrmDialog((Frame) SwingUtilities.getWindowAncestor(this), true, panel);
            dialog.setVisible(true);
        }

    }

    @Override
    public void popuniPodatke() {
        k = (Klijent) sesija.Sesija.getInstanca().getMapa().get("trenutniKlijent");
        if (k != null) {

            lblImeIPrezime.setText("Ime i prezime: " + k.getImePrezimeKlijent());
            lblDatumRodjenja.setText("Datum rodjenja: " + k.getDatumRodjenja());
            lblBrojTelefona.setText("Broj telefona: " + k.getBrojTelefona());
        }
        v = (Vozilo) sesija.Sesija.getInstanca().getMapa().get("trenutnoVozilo");
        if (v != null) {
            lblMarka.setText("Marka vozila: " + v.getMarka());

            lblKilometraza.setText("Kilometraza: " + v.getKilometraza());
            lblTipVozila.setText("Tip vozila: " + v.getTipVozila());
            lblBrojPutnila.setText("Broj putnika: " + v.getBrojPutnika());
            lblCenaPoDanu.setText("Cena po danu: " + v.getCenaPoDanu());

        }
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Rezervacija r = (Rezervacija) odk;
        if (r != null) {
            Klijent k = r.getKlijent();
            lblImeIPrezime.setText("Ime i prezime: " + k.getImePrezimeKlijent());
            lblDatumRodjenja.setText("Datum rodjenja: " + k.getDatumRodjenja());
            lblBrojTelefona.setText("Broj telefona: " + k.getBrojTelefona());

            Vozilo v = r.getVozilo();
            lblMarka.setText("Marka vozila: " + v.getMarka());
            lblKilometraza.setText("Kilometraza: " + v.getKilometraza());
            lblTipVozila.setText("Tip vozila: " + v.getTipVozila());
            lblBrojPutnila.setText("Broj putnika: " + v.getBrojPutnika());
            lblCenaPoDanu.setText("Cena po danu: " + v.getCenaPoDanu());

            txtNazivRezervacije.setText(r.getNaziv());
            txtCenaRezervacije.setText(r.getCenaRezervacije() + "");

            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(r.getDatumOd());
            dpDatumOd.setSelectedDate(gc);

            GregorianCalendar gc2 = new GregorianCalendar();
            gc2.setTime(r.getDatumDo());
            dpDatumDo.setSelectedDate(gc2);

        }
    }

    private void izmeniPolja() {
        lblMarka.setText("Marka vozila: ");
        lblKilometraza.setText("Kilometraza: ");
        lblTipVozila.setText("Tip vozila: ");
        lblBrojPutnila.setText("Broj putnika: ");
        lblCenaPoDanu.setText("Cena po danu: ");
        lblImeIPrezime.setText("Ime i prezime: ");
        lblDatumRodjenja.setText("Datum rodjenja: ");
        lblBrojTelefona.setText("Broj telefona: ");
        txtNazivRezervacije.setText(" ");
        txtCenaRezervacije.setText(" ");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzborKlijenta;
    private javax.swing.JButton btnIzborVozila;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPrikaziDetalje;
    private javax.swing.JButton btnSacuvajSve;
    private javax.swing.JButton btnUnesi;
    private datechooser.beans.DateChooserCombo dpDatum;
    private datechooser.beans.DateChooserCombo dpDatumDo;
    private datechooser.beans.DateChooserCombo dpDatumOd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnl2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojPutnila;
    private javax.swing.JLabel lblBrojTelefona;
    private javax.swing.JLabel lblCenaPoDanu;
    private javax.swing.JLabel lblCenaRezervacije;
    private javax.swing.JLabel lblDatumRezervacije;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblImeIPrezime;
    private javax.swing.JLabel lblKilometraza;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblNazivRezervacije;
    private javax.swing.JLabel lblTipVozila;
    private javax.swing.JTable tblRezervacija;
    private javax.swing.JTextField txtCenaRezervacije;
    private javax.swing.JTextField txtNazivRezervacije;
    // End of variables declaration//GEN-END:variables

    private boolean validacija(String naziv, String cena) {
        if (naziv.isEmpty() || cena.isEmpty() || naziv == "") {
            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke");
            return false;
        }
        return true;
    }

    private int daysBetween(Date datumOd, Date datumDo) {

        return (int) ((datumDo.getTime() - datumOd.getTime()) / (1000 * 60 * 60 * 24));

    }

}
