/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forma.panel;

import com.mysql.jdbc.StringUtils;
import domain.OpstaDomenskaKlasa;
import domain.Vozilo;
import domain.Zaposleni;
import forma.FrmDialog;
import forma.FrmForma;
import forma.GlavnaForma;
import forma.IPanel;
import forma.ModForme;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;

/**
 *
 * @author Sapsaj
 */
public class PnlUnosVozila extends javax.swing.JPanel implements IPanel {

    private ModForme model;

    /**
     * Creates new form PnlUnosVozila
     */
    public PnlUnosVozila(ModForme model) {
        initComponents();
        pripremiFormu(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKilometraza = new javax.swing.JLabel();
        txtKilometraza = new javax.swing.JTextField();
        lblTipVozila = new javax.swing.JLabel();
        txtTipVozila = new javax.swing.JTextField();
        lblBrojPutnika = new javax.swing.JLabel();
        txtBrojPutnika = new javax.swing.JTextField();
        lblCenaPoDanu = new javax.swing.JLabel();
        txtCenaPoDanu = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        lblMarka = new javax.swing.JLabel();
        txtMarka = new javax.swing.JTextField();

        lblKilometraza.setText("Kilometraza:");

        lblTipVozila.setText("Tip vozila:");

        lblBrojPutnika.setText("Broj putnika u vozilu:");

        lblCenaPoDanu.setText("Cena po danu:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        lblMarka.setText("Marka:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(lblCenaPoDanu)
                            .addGap(18, 18, 18)
                            .addComponent(txtCenaPoDanu))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblBrojPutnika)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBrojPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipVozila)
                                .addGap(43, 43, 43)
                                .addComponent(txtTipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblKilometraza)
                                        .addGap(43, 43, 43))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMarka)
                                        .addGap(69, 69, 69)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKilometraza, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtMarka))))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarka)
                    .addComponent(txtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKilometraza)
                    .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipVozila))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojPutnika)
                    .addComponent(txtBrojPutnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCenaPoDanu)
                    .addComponent(txtCenaPoDanu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
     
        try {
            String km = txtKilometraza.getText();
            String tipVozila = txtTipVozila.getText();
            String br = txtBrojPutnika.getText();
            String ce = txtCenaPoDanu.getText();
            String marka = txtMarka.getText();
            

            Zaposleni z = sesija.Sesija.getInstanca().getZaposleni();

            boolean val = validacija(km, tipVozila, br, ce, marka);

            if (val) {
                
                 double cena = Double.parseDouble(ce);
                 double kilometraza = Double.parseDouble(km);
                 int brojPutnika = Integer.parseInt(br);
                 
                Vozilo v = new Vozilo((long) 0, kilometraza, tipVozila, brojPutnika, cena, z, marka);
                try {
                    String poruka = Kontroler.getInstanca().unesiVozilo(v);
                    JOptionPane.showMessageDialog(this, poruka);
                    sesija.Sesija.getInstanca().getMapa().put("trenutnoVozilo", v);
                    ((FrmDialog) SwingUtilities.getWindowAncestor(this)).dispose();
                    if (((SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))) instanceof GlavnaForma) {
                        return;
                    }
                    (((FrmForma) SwingUtilities.getWindowAncestor((FrmDialog) SwingUtilities.getWindowAncestor(this)))).getPanel().popuniPodatke();
                } catch (NullPointerException e) {
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Neuspesno cuvanje");
                    Logger.getLogger(PnlUnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Morate uneti rboj");
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void pripremiFormu(ModForme model) {
        switch (model) {
            case unos:
                btnSacuvaj.setVisible(true);

                break;
            case izmena:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutnoVozilo"));
                btnSacuvaj.setVisible(false);

                break;
            case pregled:
                popuniPolja(sesija.Sesija.getInstanca().getMapa().get("trenutnoVozilo"));
                btnSacuvaj.setVisible(false);

                txtKilometraza.setEditable(false);

                txtTipVozila.setEditable(false);
                txtBrojPutnika.setEditable(false);
                txtCenaPoDanu.setEditable(false);
                txtMarka.setEditable(false);

                break;
        }
    }

    public ModForme getModel() {
        return model;
    }

    public void setModel(ModForme model) {
        this.model = model;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel lblBrojPutnika;
    private javax.swing.JLabel lblCenaPoDanu;
    private javax.swing.JLabel lblKilometraza;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblTipVozila;
    private javax.swing.JTextField txtBrojPutnika;
    private javax.swing.JTextField txtCenaPoDanu;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtMarka;
    private javax.swing.JTextField txtTipVozila;
    // End of variables declaration//GEN-END:variables

    private boolean validacija(String km, String tipVozila, String br, String ce, String marka) {

        if (km.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;
        }
        if (tipVozila.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;
        }
        if (br.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;
        }
        if (ce.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;
        }
        if (marka.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Morate uneti sve podatke!");
            return false;
        }
        
            

        return true;
    }

    @Override
    public void popuniPolja(OpstaDomenskaKlasa odk) {
        Vozilo v = (Vozilo) odk;
        txtMarka.setText(v.getMarka());
        txtKilometraza.setText(v.getKilometraza() + "");
        txtTipVozila.setText(v.getTipVozila());
        txtBrojPutnika.setText(v.getBrojPutnika() + "");
        txtCenaPoDanu.setText(v.getCenaPoDanu() + "");
    }

}
